config system global
    set hostname "FortiGate-Fictif-Single"
    set version "v7.2.4"
    set model "FG-100F"
    set serial "FG100FTK23000123"
end

config system interface
    edit "port1"
        set vdom "root"
        set ip 192.168.1.99 255.255.255.0
        set allowaccess ping https ssh
        set type physical
        set role lan
        set status up
    next
    edit "port2"
        set vdom "root"
        set ip 203.0.113.10 255.255.255.240
        set allowaccess ping
        set type physical
        set role wan
        set status up
    next
    edit "vlan10"
        set vdom "root"
        set ip 10.10.10.1 255.255.255.0
        set type vlan
        set vlanid 10
        set interface "port1"
        set role lan
        set status up
    next
end

config system zone
    edit "Zone-LAN"
        set interface "port1" "vlan10"
        set intrazone deny
    next
    edit "Zone-WAN"
        set interface "port2"
        set intrazone deny
    next
end

config firewall address
    edit "LAN-Subnet-192"
        set type subnet
        set subnet 192.168.1.0 255.255.255.0
    next
    edit "VLAN10-Subnet"
        set type subnet
        set subnet 10.10.10.0 255.255.255.0
    next
    edit "Any-Internet"
        set type subnet
        set subnet 0.0.0.0 0.0.0.0
    next
end

config firewall service custom
    edit "Custom-HTTPS"
        set protocol TCP
        set tcp-portrange 443
    next
end

config firewall policy
    edit 1
        set name "Allow-LAN-to-WAN"
        set srcintf "Zone-LAN"
        set dstintf "Zone-WAN"
        set srcaddr "LAN-Subnet-192" "VLAN10-Subnet"
        set dstaddr "Any-Internet"
        set action accept
        set service "Custom-HTTPS" "PING"
        set nat enable
        set logtraffic all
        set status enable
    next
end

config router static
    edit 1
        set dst 0.0.0.0 0.0.0.0
        set gateway 203.0.113.1
        set device "port2"
    next
end
